[ISSUE #3985]Fix cannot resolve method getSubystem in PubSubConfig and code style
apache/eventmesh pull request #3986
Opened 2023-05-20 16:27 UTC by mxsm

Fixes #3985 

### Motivation

*Explain the content here.*
*Explain why you want to make the changes and what problem you're trying to solve.*

### Modifications

- *Fix cannot resolve method getSubystem in PubSubConfig*
- *Fix code style*

### Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
- If a feature is not applicable for documentation, explain why?
- If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

2023-05-21 11:15 UTC, xwm1992 requested changes

2023-05-21 11:15 UTC, xwm1992 commented on eventmesh-connector-sdks/eventmesh-connector-sdk-java/src/main/java/org/apache/eventmesh/connector/api/config/PubSubConfig.java
> +    private String subsystem;
here don't use the subsystem, use `appId` instead which is in `PubSubConfig` class

2023-05-21 13:34 UTC, mxsm commented
@xwm1992 PTAL~

2023-05-21 15:00 UTC, xwm1992 approved these changes

2023-05-22 02:33 UTC, lrhkobe approved these changes
LGTM

2023-05-22 02:33 UTC, lrhkobe commented on eventmesh-connector-sdks/eventmesh-connector-sdk-java/src/main/java/org/apache/eventmesh/connector/util/ConfigUtil.java
What's the change of this file? There is no difference between deleted method and added method. If there are no modifications, do not submit to avoid confusion for the reviewer to understand what has been changed.

2023-05-22 02:38 UTC, merged

2023-05-22 05:52 UTC, mxsm commented on eventmesh-connector-sdks/eventmesh-connector-sdk-java/src/main/java/org/apache/eventmesh/connector/util/ConfigUtil.java
fix code style check not pass