[Feature #4032] Add Redis Connector modules
apache/eventmesh pull request #4280
Opened 2023-07-25 09:19 UTC by fabian4

Fixes #4032.

### Motivation

*Explain the content here.*
*Explain why you want to make the changes and what problem you're trying to solve.*

### Modifications

*Describe the modifications you've done.*

### Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
- If a feature is not applicable for documentation, explain why?
- If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

2023-07-25 14:27 UTC, mxsm reviewed
@fabian4 Please check code style and CI not pass

2023-07-25 15:31 UTC, Pil0tXia requested changes
Thank you for your contribution.

2023-07-25 15:31 UTC, Pil0tXia commented on eventmesh-connectors/eventmesh-connector-redis/src/main/java/org/apache/eventmesh/connector/redis/server/RedisConnectServer.java
> +            kafkaSinkApp.run(RedisSinkConnector.class);
I suggest a naming change for `kafkaSourceApp` and `kafkaSinkApp`.

2023-07-25 15:33 UTC, Pil0tXia commented on eventmesh-connectors/eventmesh-connector-redis/src/main/resources/sink-config.yml
> +    group: kafkaSink
and here.

2023-07-25 15:40 UTC, fabian4 commented
The data encoding and decoding still in progress.

2023-07-26 02:41 UTC, Alonexc commented
![image](https://github.com/apache/eventmesh/assets/91315508/68227799-deb5-44ae-88b0-29df5fa4e903)
please check checkstyle.

2023-07-26 03:19 UTC, fabian4 commented
> ![image](https://user-images.githubusercontent.com/91315508/256094356-68227799-deb5-44ae-88b0-29df5fa4e903.png) please check checkstyle.

Just fixed it.

BTW is there any way to check it automatically in my local IDEA. How to make it import the dependancy with the order we need as the rules said.

2023-07-26 05:38 UTC, Pil0tXia commented
@fabian4 Please see https://eventmesh.apache.org/zh/community/contribute/contribute

2023-07-26 15:15 UTC, mxsm approved these changes
LGTM

2023-07-27 07:10 UTC, xwm1992 approved these changes

2023-07-27 07:11 UTC, merged