Update EventMeshTcp2Client.java
apache/eventmesh pull request #4465
Opened 2023-09-26 12:37 UTC by Monika-Sivakumar-3

Make anonymous inner class a lambda[EventMeshTcp2Client]

Fixes #3399 .

### Motivation

*Make anonymous inner class a lambda[EventMeshTcp2Client]*

### Modifications

*Make anonymous inner class a lambda*

### Documentation

- Does this pull request introduce a new feature? no
- If yes, how is the feature documented? not applicable

2023-09-26 13:10 UTC, Pil0tXia requested changes
Welcome to EventMesh community. You haven't finished all the works mentioned in the issue. You may turn this PR into a `draft` and then mark it as `requesting for review` after it is completed.

By the way, please revise your article title according to the standard format.

2023-09-26 13:10 UTC, Pil0tXia commented on eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/EventMeshTcp2Client.java
>              });
Please remove this blank line.

2023-09-27 03:30 UTC, mxsm requested changes
@Monika-Sivakumar-3  Please fix code style

2023-09-27 06:49 UTC, mxsm reviewed
@Monika-Sivakumar-3  Please run checkstyleMain with IDEA
![image](https://github.com/apache/eventmesh/assets/15797831/e2cf381d-f62e-4cdd-a27d-24582dda48f5)
find the code style error and fix it.

2023-10-26 01:34 UTC, xwm1992 commented
For there is no response, I'll close this pr.

2023-10-26 01:34 UTC, closed without merging