Fix patch issue3825
apache/eventmesh pull request #4525
Opened 2023-10-31 14:10 UTC by tooo-bad

I tried to fix issue 3825, but only two lines of code have changed. I'm not sure if this is correct.

2023-10-31 14:26 UTC, Pil0tXia commented
@tooo-bad Please reference other pull requests for a standard format of PR title and `Fixes` keyword.

2023-10-31 14:28 UTC, Pil0tXia requested changes

2023-10-31 14:28 UTC, Pil0tXia commented on eventmesh-storage-plugin/eventmesh-storage-standalone/src/main/java/org/apache/eventmesh/storage/standalone/broker/model/TopicMetadata.java
Better have a newline between these two members to match eventmesh codestyle.

2023-10-31 15:52 UTC, mxsm reviewed
@tooo-bad  Thanks for your contribution. Please fix CI and link issue use fix#xxxx（xxxx is issue number）

2023-11-01 02:08 UTC, tooo-bad commented
Okay, I will resubmit the PR.

2023-11-01 02:38 UTC, tooo-bad commented
I have added a newline, please check.

2023-11-01 03:16 UTC, Pil0tXia requested changes

2023-11-01 03:16 UTC, Pil0tXia commented on eventmesh
@tooo-bad It seems that you've added a git submodule. Please remove it.

2023-11-01 04:07 UTC, tooo-bad commented on eventmesh
I have searched the config file for no information about submodules, and there is no .gitmodules file in the root directory.

2023-11-01 04:49 UTC, closed without merging